test_that("checks_to_summary returns severity column", {
  x <- generate_dummy_adppk(study_type = "SAD", n_subj = 10, seed = 8)
  out <- run_checks(x$adppk, x$addose, selected = c("required_vars", "duplicates"))
  s <- checks_to_summary(out)
  expect_true(all(c("check_id", "rule_version", "severity", "status", "passed", "n_issue", "message") %in% names(s)))
  expect_equal(nrow(s), 2)
})

test_that("generate_check_report_html writes expected content", {
  x <- generate_dummy_adppk(study_type = "SAD", n_subj = 10, seed = 9)
  out <- run_checks(x$adppk, x$addose, selected = c("required_vars", "duplicates"))
  f <- tempfile(fileext = ".html")
  generate_check_report_html(x$adppk, out, f)
  expect_true(file.exists(f))
  txt <- paste(readLines(f, warn = FALSE), collapse = "\n")
  expect_match(txt, "pkchk checklist report")
  expect_match(txt, "Package</b>: pkchk")
  expect_match(txt, "<h2>Summary</h2>")
  expect_match(txt, "required_vars")
  expect_match(txt, "duplicates")
})
